#!/bin/bash

set -euo pipefail
. /.functions

# For SSL support
set_or_default SSL_DIR "/.ssl"

# No pre-set certificate, so we need to obtain one from the ACME service
init_ssl

CN="$(openssl x509 -in "${INTERNALTLS_SERVER_PEM_PATH}" -subject -noout -nameopt RFC2253 2>&1)" || fail "Failed to get the SSL certificate's CN (rc=${?}): ${CN}"
export INTERNALTLS_SNI="${CN##*=}"

#
# Slight adjustment for Minio stuff
#
export EXPAND_URLS_PREFIX="MINIO_"
. <(/usr/local/bin/expand-urls)

[ -n "${MINIO_URL_HOST:-}" ] && export MINIO_ADDRESS="${MINIO_URL_HOST}"
[ -n "${MINIO_URL_PORT:-}" ] && export MINIO_PORT="${MINIO_URL_PORT}"

set_or_default MILVUS_MODE "standalone"

# Run the thing!
[ ${#} -gt 0 ] || set -- "run" "${MILVUS_MODE}"
execute milvus "${@}"
